# Generated by Django 5.0.6 on 2024-07-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("product_price", models.FloatField(blank=True, null=True)),
                ("product_status", models.CharField(default="0", max_length=11)),
                ("product_stock", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateTimeField(blank=True, null=True)),
                ("sale_items_total", models.IntegerField(default=0)),
                (
                    "sale_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale_Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_price", models.FloatField()),
                ("item_qty", models.IntegerField(default=0)),
                ("is_verify", models.IntegerField(default=0)),
                (
                    "product_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.products",
                    ),
                ),
                (
                    "sale_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.sales",
                    ),
                ),
            ],
        ),
    ]
